---

name: CI

on: push

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        uses: rust
        env:
          MDBOOK_VERSION: 0.3.0
        run: |
          cargo install mdbook --vers ${MDBOOK_VERSION}
          mdbook build

  Deploy:
    runs-on: ubuntu-latest

    needs:
      - Build

    if: github.ref == 'refs/heads/master'

    steps:
      - name: Setup Hosting
        run: |
          touch docs/.nojekyll &&
          echo "tech-docs.system76.com" > docs/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./book
