---

name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - '!master'

jobs:
  Build:
    runs-on: ubuntu-latest
    container: rust:slim

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        env:
          MDBOOK_VERSION: 0.3.0
        run: |
          cargo install mdbook --vers ${MDBOOK_VERSION}
          make book
